name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        submodules: true  

    - name: Build
      shell: bash -l {0}
      run: |
        ./build.sh

    - name: Run tests
      shell: bash -l {0}
      run: |
        test/test.sh


    